name: Generate GitHub Stats Images
on:
  schedule:
    # Runs once every 24 hours (adjust cron as you like)
    - cron: "0 0 * * *"
  workflow_dispatch: {}   # lets you trigger it manually from the Actions tab
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate images
        uses: Abhishek-Singh-2008/github-stats@master
        with:
          username: Abhishek-Singh-2008
          exclude_repos: Abhishek-Singh-2008/Abhishek-Singh-2008
          # exclude_langs: html,css        # optional, uncomment to exclude langs
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
